spring:
  application:
    name: DiscordBotService

discord:
  bot:
    token:
      engineers: ${DISCORD_ENGINEERS_API_KEY}
      rust: ${DISCORD_RUST_API_KEY}

backend:
  api:
    url: http://${SERVER_IP}:${SERVER_PORT}/api/v1/analytics
    key: ${SERVER_API_KEY}