spring:
  application:
    name: DiscordBotService

discord:
  bot:
    token: ${DISCORD_API_KEY}

backend:
  api:
    url: http://${SERVER_IP}:${SERVER_PORT}/api/v1/analytics/engineers
    key: ${SERVER_API_KEY}